export const DEFAULT_STAFF_MODULES = [
  {
    id: 0,
    parentId: null,
    moduleKey: 'dashboard',
    label: 'Dashboard',
    path: '/staff/dashboard',
    icon: 'layout',
    allowedRoles: ['FRONT_DESK', 'MANAGER', 'ADMIN'],
    sortOrder: 5,
    enabled: true,
    children: [],
  },
  {
    id: 1,
    parentId: null,
    moduleKey: 'arrivals',
    label: 'Arrivals',
    path: '/staff/arrivals',
    icon: 'calendar',
    allowedRoles: ['FRONT_DESK', 'MANAGER', 'ADMIN'],
    sortOrder: 10,
    enabled: true,
    children: [],
  },
  {
    id: 2,
    parentId: null,
    moduleKey: 'rooms',
    label: 'Rooms',
    path: '#',
    icon: 'bed',
    allowedRoles: ['MANAGER', 'ADMIN'],
    sortOrder: 20,
    enabled: true,
    children: [
      {
        id: 20,
        parentId: 2,
        moduleKey: 'rooms-config',
        label: 'Room configuration',
        path: '/staff/rooms/config',
        icon: 'settings',
        allowedRoles: ['MANAGER', 'ADMIN'],
        sortOrder: 5,
        enabled: true,
        children: [],
      },
      {
        id: 21,
        parentId: 2,
        moduleKey: 'rooms-catalog',
        label: 'Create room',
        path: '/staff/rooms/catalog',
        icon: 'bed',
        allowedRoles: ['MANAGER', 'ADMIN'],
        sortOrder: 10,
        enabled: true,
        children: [],
      },
      {
        id: 22,
        parentId: 2,
        moduleKey: 'rooms-operations',
        label: 'View and update room',
        path: '/staff/rooms/operations',
        icon: 'bed',
        allowedRoles: ['MANAGER', 'ADMIN'],
        sortOrder: 20,
        enabled: true,
        children: [],
      },
    ],
  },
  {
    id: 3,
    parentId: null,
    moduleKey: 'settings',
    label: 'Settings',
    path: '/staff/settings',
    icon: 'settings',
    allowedRoles: ['ADMIN'],
    sortOrder: 30,
    enabled: true,
    children: [],
  },
  {
    id: 4,
    parentId: null,
    moduleKey: 'users',
    label: 'Staff users',
    path: '/staff/users',
    icon: 'users',
    allowedRoles: ['ADMIN'],
    sortOrder: 40,
    enabled: true,
    children: [],
  },
  {
    id: 5,
    parentId: null,
    moduleKey: 'modules',
    label: 'Sidebar modules',
    path: '/staff/modules',
    icon: 'layout',
    allowedRoles: ['ADMIN'],
    sortOrder: 50,
    enabled: true,
    children: [],
  },
]

export const STAFF_NAV_ICONS = [
  { value: 'calendar', label: 'Calendar' },
  { value: 'bed', label: 'Bed' },
  { value: 'settings', label: 'Settings' },
  { value: 'users', label: 'Users' },
  { value: 'layout', label: 'Layout' },
]
