export const DEFAULT_STAFF_MODULES = [
  {
    id: 0,
    parentId: null,
    moduleKey: 'dashboard',
    label: 'Dashboard',
    path: '/staff/dashboard',
    icon: 'layout',
    allowedRoles: ['FRONT_DESK', 'MANAGER', 'ADMIN'],
    sortOrder: 5,
    enabled: true,
    children: [],
  },
  {
    id: 1,
    parentId: null,
    moduleKey: 'arrivals',
    label: 'Arrivals',
    path: '#',
    icon: 'calendar',
    allowedRoles: ['FRONT_DESK', 'MANAGER', 'ADMIN'],
    sortOrder: 10,
    enabled: true,
    children: [
      {
        id: 11,
        parentId: 1,
        moduleKey: 'arrivals-today',
        label: "Today's arrivals",
        path: '/staff/arrivals',
        icon: 'calendar',
        allowedRoles: ['FRONT_DESK', 'MANAGER', 'ADMIN'],
        sortOrder: 10,
        enabled: true,
        children: [],
      },
      {
        id: 13,
        parentId: 1,
        moduleKey: 'arrivals-guests',
        label: 'Guests',
        path: '/staff/guests',
        icon: 'users',
        allowedRoles: ['FRONT_DESK', 'MANAGER', 'ADMIN'],
        sortOrder: 30,
        enabled: true,
        children: [],
      },
    ],
  },
  {
    id: 6,
    parentId: null,
    moduleKey: 'bookings',
    label: 'Bookings',
    path: '#',
    icon: 'layout',
    allowedRoles: ['FRONT_DESK', 'MANAGER', 'ADMIN'],
    sortOrder: 12,
    enabled: true,
    children: [
      {
        id: 61,
        parentId: 6,
        moduleKey: 'bookings-all',
        label: 'All bookings',
        path: '/staff/bookings',
        icon: 'layout',
        allowedRoles: ['FRONT_DESK', 'MANAGER', 'ADMIN'],
        sortOrder: 10,
        enabled: true,
        children: [],
      },
    ],
  },
  {
    id: 2,
    parentId: null,
    moduleKey: 'rooms',
    label: 'Rooms',
    path: '#',
    icon: 'bed',
    allowedRoles: ['MANAGER', 'ADMIN'],
    sortOrder: 20,
    enabled: true,
    children: [
      {
        id: 20,
        parentId: 2,
        moduleKey: 'rooms-config',
        label: 'Room configuration',
        path: '/staff/rooms/config',
        icon: 'settings',
        allowedRoles: ['MANAGER', 'ADMIN'],
        sortOrder: 5,
        enabled: true,
        children: [],
      },
      {
        id: 21,
        parentId: 2,
        moduleKey: 'rooms-catalog',
        label: 'Create room',
        path: '/staff/rooms/catalog',
        icon: 'bed',
        allowedRoles: ['MANAGER', 'ADMIN'],
        sortOrder: 10,
        enabled: true,
        children: [],
      },
      {
        id: 22,
        parentId: 2,
        moduleKey: 'rooms-operations',
        label: 'View and update room',
        path: '/staff/rooms/operations',
        icon: 'bed',
        allowedRoles: ['MANAGER', 'ADMIN'],
        sortOrder: 20,
        enabled: true,
        children: [],
      },
      {
        id: 23,
        parentId: 2,
        moduleKey: 'rooms-extras',
        label: 'Extras',
        path: '/staff/rooms/extras',
        icon: 'bed',
        allowedRoles: ['MANAGER', 'ADMIN'],
        sortOrder: 15,
        enabled: true,
        children: [],
      },
    ],
  },
  {
    id: 3,
    parentId: null,
    moduleKey: 'settings',
    label: 'Settings',
    path: '#',
    icon: 'settings',
    allowedRoles: ['ADMIN'],
    sortOrder: 30,
    enabled: true,
    children: [
      {
        id: 31,
        parentId: 3,
        moduleKey: 'settings-general',
        label: 'General',
        path: '/staff/settings',
        icon: 'settings',
        allowedRoles: ['ADMIN'],
        sortOrder: 5,
        enabled: true,
        children: [],
      },
      {
        id: 32,
        parentId: 3,
        moduleKey: 'settings-audit',
        label: 'Audit logs',
        path: '/staff/settings/audit',
        icon: 'layout',
        allowedRoles: ['ADMIN'],
        sortOrder: 10,
        enabled: true,
        children: [],
      },
      {
        id: 33,
        parentId: 3,
        moduleKey: 'settings-refund-policy',
        label: 'Refund policy',
        path: '/staff/settings/refund-policy',
        icon: 'settings',
        allowedRoles: ['ADMIN'],
        sortOrder: 7,
        enabled: true,
        children: [],
      },
      {
        id: 35,
        parentId: 3,
        moduleKey: 'settings-promos',
        label: 'Promos & discounts',
        path: '/staff/settings/promos',
        icon: 'settings',
        allowedRoles: ['ADMIN'],
        sortOrder: 8,
        enabled: true,
        children: [],
      },
      {
        id: 34,
        parentId: 3,
        moduleKey: 'branding',
        label: 'Branding',
        path: '/staff/branding',
        icon: 'palette',
        allowedRoles: ['ADMIN'],
        sortOrder: 15,
        enabled: true,
        children: [],
      },
    ],
  },
  {
    id: 4,
    parentId: null,
    moduleKey: 'users',
    label: 'Staff users',
    path: '/staff/users',
    icon: 'users',
    allowedRoles: ['ADMIN'],
    sortOrder: 40,
    enabled: true,
    children: [],
  },
  {
    id: 5,
    parentId: null,
    moduleKey: 'modules',
    label: 'Sidebar modules',
    path: '/staff/modules',
    icon: 'layout',
    allowedRoles: ['ADMIN'],
    sortOrder: 50,
    enabled: true,
    children: [],
  },
]

export const STAFF_NAV_ICONS = [
  { value: 'calendar', label: 'Calendar' },
  { value: 'bed', label: 'Bed' },
  { value: 'settings', label: 'Settings' },
  { value: 'users', label: 'Users' },
  { value: 'layout', label: 'Layout' },
  { value: 'palette', label: 'Palette' },
]
